// Export all schemas
export * from './users.schema';
export * from './modules.schema';
export * from './resources.schema';
export * from './videos.schema';
export * from './quizzes.schema';
export * from './flashcards.schema';
export * from './slides.schema';
export * from './infographics.schema';
export * from './reports.schema';
export * from './audio.schema';
export * from './games.schema';
export * from './progress.schema';
export * from './quiz-attempts.schema';
export * from './search.schema';
